# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            Kevin Shawn
tagline:          'Stop Crying Make Yourself Better'
description:      'Be Happy Everyday'
url:              http://weibo.com/u/2406493902/home?wvr=5

author:
  name:           'Kevin Shawn'
  url:            https://github.com/KevinShawn

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : KSN