# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            Leon
tagline:          ''
description:      'Be Happy Everyday!Make Yourself Better'
url:              http://weibo.com/u/2406493902/home?wvr=5

author:
  name:           'Leon'
  url:            https://github.com/KevinShawn

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : Leon